import type { Schema } from "@electric-circuits/protocol";

export const schema: Schema = {
  tables: {
    activity_log: {
      columns: {
        id: { type: "int" },
        source: { type: "text" },
        type: { type: "text" },
        summary: { type: "text" },
        detail: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    agent_runs: {
      columns: {
        id: { type: "text" },
        source: { type: "text" },
        agent_id: { type: "text" },
        project: { type: "text" },
        cwd: { type: "text" },
        operation: { type: "text" },
        started_at: { type: "text" },
        ended_at: { type: "text" },
        duration_ms: { type: "int" },
        prompt_count: { type: "int" },
        error: { type: "text" },
        outcome: { type: "text" },
        outcome_score: { type: "float" },
        outcome_source: { type: "text" },
        drifted: { type: "bool" },
        dead_end: { type: "bool" },
        headline: { type: "text" },
        summary: { type: "text" },
        judged_at: { type: "text" },
        raw_ref: { type: "text" },
      },
      primaryKey: "id",
    },
    portfolio_positions: {
      columns: {
        id: { type: "text" },
        symbol: { type: "text" },
        name: { type: "text" },
        qty: { type: "float" },
        price: { type: "float" },
        market_value: { type: "float" },
        asset_class: { type: "text" },
        institution: { type: "text" },
        account_name: { type: "text" },
        account_kind: { type: "text" },
        position_kind: { type: "text" },
        as_of_date: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "id",
    },
    portfolio_trades: {
      columns: {
        trade_id: { type: "text" },
        symbol: { type: "text" },
        description: { type: "text" },
        side: { type: "text" },
        quantity: { type: "float" },
        price: { type: "float" },
        proceeds: { type: "float" },
        date: { type: "text" },
        is_option: { type: "bool" },
        option_type: { type: "text" },
        option_strike: { type: "float" },
        option_expiry: { type: "text" },
        institution: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "trade_id",
    },
    portfolio_balances: {
      columns: {
        account_id: { type: "text" },
        institution: { type: "text" },
        type: { type: "text" },
        balance: { type: "float" },
        as_of_date: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "account_id",
    },
    portfolio_transactions: {
      columns: {
        txn_id: { type: "text" },
        account_id: { type: "text" },
        institution: { type: "text" },
        date: { type: "text" },
        amount: { type: "float" },
        merchant: { type: "text" },
        raw_description: { type: "text" },
        category: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "txn_id",
    },
    portfolio_net_worth: {
      columns: {
        date: { type: "text" },
        total_assets: { type: "float" },
        total_liabilities: { type: "float" },
        net_worth: { type: "float" },
        cash: { type: "float" },
        invested: { type: "float" },
        by_asset_class: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "date",
    },
    portfolio_benchmarks: {
      columns: {
        symbol: { type: "text" },
        date: { type: "text" },
        close: { type: "float" },
        updated_at: { type: "text" },
      },
      primaryKey: "symbol,date",
    },
    portfolio_allocation: {
      columns: {
        asset_class: { type: "text" },
        market_value: { type: "float" },
        target_pct: { type: "float" },
        current_pct: { type: "float" },
        drift_pct: { type: "float" },
        updated_at: { type: "text" },
      },
      primaryKey: "asset_class",
    },
    judgment_collections: {
      columns: {
        id: { type: "text" },
        name: { type: "text" },
        kind: { type: "text" },
        description: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    judgments: {
      columns: {
        id: { type: "text" },
        activity_id: { type: "int" },
        span_start: { type: "text" },
        span_end: { type: "text" },
        verdict: { type: "text" },
        comment: { type: "text" },
        collection_id: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    repos: {
      columns: {
        id:         { type: "text" },
        name:       { type: "text" },
        path:       { type: "text" },
        git_remote: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    thread_meta: {
      columns: {
        thread_id: { type: "text" },
        channel_id: { type: "text" },
        lifecycle: { type: "text" },
        state: { type: "text" },
        enabled_workflows: { type: "text" },
        research_mode: { type: "text" },
        priority: { type: "text" },
        assignee: { type: "text" },
        repo_id:  { type: "text" },
        labels:   { type: "text" },
        promoted_to: { type: "text" },
        archived_at: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "thread_id",
    },
    channels: {
      columns: {
        id: { type: "text" },
        name: { type: "text" },
        description: { type: "text" },
        default_lifecycle: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    channel_members: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        member_type: { type: "text" },
        member_name: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    messages: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        author: { type: "text" },
        body: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    channel_read_state: {
      columns: {
        viewer_id: { type: "text" },
        channel_id: { type: "text" },
        last_read_at: { type: "text" },
      },
      primaryKey: "viewer_id,channel_id",
    },
    thread_plans: {
      columns: {
        id: { type: "text" },
        thread_id: { type: "text" },
        title: { type: "text" },
        status: { type: "text" },
        sort_order: { type: "int" },
        created_at: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "id",
    },
    thread_workflow_steps: {
      columns: {
        id: { type: "text" },
        thread_id: { type: "text" },
        step_label: { type: "text" },
        status: { type: "text" },
        detail: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    thread_promotions: {
      columns: {
        id: { type: "text" },
        thread_id: { type: "text" },
        repo_path: { type: "text" },
        status: { type: "text" },
        error_detail: { type: "text" },
        agent_provider: { type: "text" },
        agent_model: { type: "text" },
        progress: { type: "text" },
        created_at: { type: "text" },
        completed_at: { type: "text" },
      },
      primaryKey: "id",
    },
    thread_artifacts: {
      columns: {
        id: { type: "text" },
        thread_id: { type: "text" },
        title: { type: "text" },
        kind: { type: "text" },
        content: { type: "text" },
        version: { type: "int" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    // High-volume, disposable agent activity trace. POLLED via the thread-extras
    // API (NOT a held Electric *_SHAPE — ADR-003 shape budget). Retention: the
    // producer prunes to the last few runs per thread on each new run; see
    // pruneThreadActivity() in api/channels/trigger/route.ts.
    thread_activity_events: {
      columns: {
        id: { type: "text" },
        thread_id: { type: "text" },
        run_id: { type: "text" },
        seq: { type: "int" },
        kind: { type: "text" },
        label: { type: "text" },
        detail: { type: "text" },
        status: { type: "text" },
        created_at: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "id",
    },
    // ── Graph Continuity (Phase 1) ──────────────────────────────────
    graph_events: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        kind: { type: "text" },
        actor: { type: "text" },
        payload: { type: "text" },
        caused_by: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_sources: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        kind: { type: "text" },
        ref_id: { type: "text" },
        content: { type: "text" },
        author: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_observations: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        source_id: { type: "text" },
        category: { type: "text" },
        text: { type: "text" },
        confidence: { type: "float" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_memory_candidates: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        observation_id: { type: "text" },
        text: { type: "text" },
        category: { type: "text" },
        confidence: { type: "float" },
        status: { type: "text" },
        resolved_by: { type: "text" },
        resolution_rationale: { type: "text" },
        resolved_at: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_memory_items: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        candidate_id: { type: "text" },
        text: { type: "text" },
        category: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_decisions: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        statement: { type: "text" },
        rationale: { type: "text" },
        evidence: { type: "text" },
        status: { type: "text" },
        supersedes: { type: "text" },
        resolved_by: { type: "text" },
        resolution_rationale: { type: "text" },
        created_at: { type: "text" },
        resolved_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_proposals: {
      columns: {
        id: { type: "text" },
        channel_id: { type: "text" },
        thread_id: { type: "text" },
        hypothesis: { type: "text" },
        capability_ids: { type: "text" },
        changes: { type: "text" },
        evidence: { type: "text" },
        status: { type: "text" },
        resolved_by: { type: "text" },
        resolution_rationale: { type: "text" },
        created_at: { type: "text" },
        resolved_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_relations: {
      columns: {
        id: { type: "text" },
        type: { type: "text" },
        source_id: { type: "text" },
        target_id: { type: "text" },
        created_at: { type: "text" },
      },
      primaryKey: "id",
    },
    graph_capability_state: {
      columns: {
        id: { type: "text" },
        capability_id: { type: "text" },
        scope_type: { type: "text" },
        scope_id: { type: "text" },
        value: { type: "text" },
        source_proposal_id: { type: "text" },
        updated_by: { type: "text" },
        created_at: { type: "text" },
        updated_at: { type: "text" },
      },
      primaryKey: "id",
    },
  },
};
