[package]
name = "buzz-create-ws"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buzz-create-ws"
path = "src/main.rs"

[[bin]]
name = "buzz-bind-repo"
path = "src/bind_repo.rs"

[dependencies]
nostr = "0.37"
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"] }
futures-util = "0.3"
rustls = { version = "0.23", features = ["ring"] }
