import { access, readFile } from "node:fs/promises";
import path from "node:path";

export type ProjectGrounding = {
  root: string;
  packageRoot: string | null;
  database: string;
  serviceWorker: string;
  prismaSchema: boolean;
  framework: string;
  evidence: string[];
};

async function exists(target: string): Promise<boolean> {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
}

export async function collectProjectGrounding(cwd: string): Promise<ProjectGrounding> {
  const root = path.resolve(cwd);
  const candidates = [root, path.join(root, "dashboard")];
  const packageRoot =
    (await Promise.all(candidates.map(async (candidate) => ({
      candidate,
      found: await exists(path.join(candidate, "package.json")),
    })))).find((entry) => entry.found)?.candidate || null;

  let dependencies: Record<string, string> = {};
  if (packageRoot) {
    const parsed = JSON.parse(await readFile(path.join(packageRoot, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    dependencies = { ...parsed.dependencies, ...parsed.devDependencies };
  }

  const relative = (target: string) => packageRoot ? path.relative(packageRoot, target) : target;
  const prismaPath = packageRoot ? path.join(packageRoot, "prisma", "schema.prisma") : "";
  const swPath = packageRoot ? path.join(packageRoot, "src", "app", "sw.ts") : "";
  const prismaSchema = Boolean(prismaPath && await exists(prismaPath));
  const hasServiceWorker = Boolean(swPath && await exists(swPath));
  const evidence = [
    ...(packageRoot ? ["package.json"] : []),
    ...(prismaSchema ? [relative(prismaPath)] : []),
    ...(hasServiceWorker ? [relative(swPath)] : []),
  ];

  return {
    root,
    packageRoot,
    database: dependencies.pg ? "PostgreSQL (pg)" : prismaSchema ? "Prisma" : "Unknown",
    serviceWorker: hasServiceWorker
      ? dependencies["@serwist/next"]
        ? `${relative(swPath)} (Serwist)`
        : relative(swPath)
      : "None detected",
    prismaSchema,
    framework: dependencies.next ? "Next.js" : "Unknown",
    evidence,
  };
}

export function renderProjectGrounding(grounding: ProjectGrounding): string {
  return [
    "Verified project grounding (generated by the server; do not contradict without evidence):",
    `- Inspected root: ${grounding.root}`,
    `- Package root: ${grounding.packageRoot || "not found"}`,
    `- Framework: ${grounding.framework}`,
    `- Database/data layer: ${grounding.database}`,
    `- Existing service worker: ${grounding.serviceWorker}`,
    `- Prisma schema present: ${grounding.prismaSchema ? "yes" : "no"}`,
    `- Evidence files: ${grounding.evidence.join(", ") || "none"}`,
  ].join("\n");
}

export function evaluatePlanApproval(input: {
  decisionsNeeded: string[];
  groundingEvidence: string[];
  unverifiedAssumptions: string[];
}): { ok: true } | { ok: false; error: string } {
  const openCount = input.decisionsNeeded.length;
  const assumptionCount = input.unverifiedAssumptions.length;
  const missingEvidence = input.groundingEvidence.length === 0;
  if (openCount || assumptionCount || missingEvidence) {
    const parts = [
      ...(missingEvidence ? ["record verified grounding evidence"] : []),
      ...(openCount ? [`Resolve ${openCount} open decision${openCount === 1 ? "" : "s"}`] : []),
      ...(assumptionCount
        ? [`verify ${assumptionCount} unsupported assumption${assumptionCount === 1 ? "" : "s"}`]
        : []),
    ];
    return {
      ok: false,
      error: `${parts.join(" and ")} before approving this plan. Add feedback, rerun the challenge, and confirm the corrected plan.`,
    };
  }
  return { ok: true };
}
